name: Tests
on: [push, pull_request]
jobs:
  stylelint:
    name: runner / stylelint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: haya14busa/action-cond@v1
        id: reporter
        with:
          cond: ${{ github.event_name == 'pull_request' }}
          if_true: "github-pr-review"
          if_false: "github-check"
      - name: stylelint
        uses: reviewdog/action-stylelint@v1
        with:
          reporter: ${{ steps.reporter.outputs.value }}
          stylelint_input: 'ckanext/depositar_theme/fanstatic/**/*.{less,scss}'
